require 'Items/ProceduralDistributions'

table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "Autotsar.ATATuningFordMustang");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 0.5);
table.insert(ProceduralDistributions.list["CrateMagazines"].items, "Autotsar.ATATuningFordMustang");
table.insert(ProceduralDistributions.list["CrateMagazines"].items, 0.5);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Autotsar.ATATuningFordMustang");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.5);
table.insert(ProceduralDistributions.list["LibraryBooks"].items, "Autotsar.ATATuningFordMustang");
table.insert(ProceduralDistributions.list["LibraryBooks"].items, 0.5);
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, "Autotsar.ATATuningFordMustang");
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, 0.1);
table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, "Autotsar.ATATuningFordMustang");
table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, 0.1);
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, "Autotsar.ATATuningFordMustang");
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, 0.5);
table.insert(ProceduralDistributions.list["MechanicShelfBooks"].items, "Autotsar.ATATuningFordMustang");
table.insert(ProceduralDistributions.list["MechanicShelfBooks"].items, 0.5);
table.insert(ProceduralDistributions.list["MechanicShelfBooks"].junk.items, "Autotsar.ATATuningFordMustang");
table.insert(ProceduralDistributions.list["MechanicShelfBooks"].junk.items, 0.5);
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, "Autotsar.ATATuningFordMustang");
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, 0.5);
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, "Autotsar.ATATuningFordMustang");
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, 0.1);
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, "Autotsar.ATATuningFordMustang");
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, 0.1);
table.insert(ProceduralDistributions.list["StoreShelfMechanics"].items, "Autotsar.ATATuningFordMustang");
table.insert(ProceduralDistributions.list["StoreShelfMechanics"].items, 0.5);
table.insert(ProceduralDistributions.list["ToolStoreBooks"].items, "Autotsar.ATATuningFordMustang");
table.insert(ProceduralDistributions.list["ToolStoreBooks"].items, 0.5);
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, "Autotsar.ATATuningFordMustang");
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, 0.5);
table.insert(ProceduralDistributions.list["CampingStoreBooks"].items, "Autotsar.ATATuningFordMustang");
table.insert(ProceduralDistributions.list["CampingStoreBooks"].items, 0.5);
table.insert(ProceduralDistributions.list["JanitorMisc"].items, "Autotsar.ATATuningFordMustang");
table.insert(ProceduralDistributions.list["JanitorMisc"].items, 0.5);

-- ATAMustang66BullbarItem
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Autotsar.ATAMustang66BullbarItem");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.75);
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Autotsar.ATAMustang66BullbarItem");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.75);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Autotsar.ATAMustang66BullbarItem");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.75);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].junk.items, "Autotsar.ATAMustang66BullbarItem");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].junk.items, 0.75);
table.insert(ProceduralDistributions.list["MechanicShelfWheels"].items, "Autotsar.ATAMustang66BullbarItem");
table.insert(ProceduralDistributions.list["MechanicShelfWheels"].items, 0.75);


-- ATAMustang66REngineDoor3
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Autotsar.ATAMustang66REngineDoor3");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.5);
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Autotsar.ATAMustang66REngineDoor3");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.5);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Autotsar.ATAMustang66REngineDoor3");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.5);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].junk.items, "Autotsar.ATAMustang66REngineDoor3");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].junk.items, 0.5);
table.insert(ProceduralDistributions.list["MechanicShelfWheels"].items, "Autotsar.ATAMustang66REngineDoor3");
table.insert(ProceduralDistributions.list["MechanicShelfWheels"].items, 0.5);

-- ATAMustang66MEngineDoor3
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Autotsar.ATAMustang66MEngineDoor3");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.5);
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Autotsar.ATAMustang66MEngineDoor3");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.5);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Autotsar.ATAMustang66MEngineDoor3");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.5);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].junk.items, "Autotsar.ATAMustang66MEngineDoor3");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].junk.items, 0.5);
table.insert(ProceduralDistributions.list["MechanicShelfWheels"].items, "Autotsar.ATAMustang66MEngineDoor3");
table.insert(ProceduralDistributions.list["MechanicShelfWheels"].items, 0.5);


-- ATAMustang66TrunkDoor3
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Autotsar.ATAMustang66TrunkDoor3");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.5);
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Autotsar.ATAMustang66TrunkDoor3");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.5);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Autotsar.ATAMustang66TrunkDoor3");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.5);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].junk.items, "Autotsar.ATAMustang66TrunkDoor3");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].junk.items, 0.5);
table.insert(ProceduralDistributions.list["MechanicShelfWheels"].items, "Autotsar.ATAMustang66TrunkDoor3");
table.insert(ProceduralDistributions.list["MechanicShelfWheels"].items, 0.5);